import type { MetadataRoute } from 'next';

/**
 * Dynamic robots.txt generated by Next.js.
 * Replaces the static public/robots.txt for better maintainability.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: '*',
      allow: '/',
      disallow: [
        '/api/',
        '/auth/',
        '/complete-profile',
        '/verify-email',
        '/verify-otp',
        '/reset-password',
        '/forgot-password',
        '/sso-callback',
        '/sso-callback/',
        '/payment-success',
        '/profile',
        '/payments',
        '/publish',
        '/home',
        '/nearby',
      ],
    },
    sitemap: 'https://keyhome.app/sitemap.xml',
  };
}
