import type { MetadataRoute } from 'next';
import { absoluteUrl } from '@/lib/site-url';

/**
 * Dynamic robots.txt generated by Next.js.
 * Replaces the static public/robots.txt for better maintainability.
 *
 * /home and /nearby stay crawlable (guest-accessible discovery pages).
 * Owner panel and auth flows stay disallowed to save crawl budget.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: '*',
      allow: '/',
      disallow: [
        '/api/',
        '/auth/',
        '/verify-email',
        '/verify-otp',
        '/reset-password',
        '/forgot-password',
        '/sso-callback',
        '/sso-callback/',
        '/choose-organization',
        '/link-account-callback',
        '/payment-success',
        '/payment/return',
        '/credits/',
        '/profile',
        '/payments',
        '/publish',
        '/messages/',
        '/my/',
        '/owner/',
      ],
    },
    sitemap: absoluteUrl('/sitemap.xml'),
  };
}
