'use client';

import createCache from '@emotion/cache';
import { CacheProvider } from '@emotion/react';
import { useServerInsertedHTML } from 'next/navigation';
import { useRef, useState } from 'react';

interface Props {
  nonce: string;
  children: React.ReactNode;
}

/**
 * MuiEmotionRegistry — nonce-aware Emotion cache for MUI in the Next.js App Router.
 *
 * Problem: MUI injects <style> tags at runtime via Emotion. Without a nonce those
 * tags are blocked by the Content-Security-Policy `style-src` directive, causing
 * MUI components to render without any styles.
 *
 * Solution: Create a custom Emotion cache that stamps every injected <style> tag
 * with the per-request nonce generated by src/proxy.ts. `useServerInsertedHTML`
 * serialises SSR styles into the HTML stream; client-side styles use the same
 * nonce-aware cache, so hydration styles also carry the correct nonce attribute.
 *
 * Usage: Wrap the MuiThemeProvider (or the entire Providers tree) with this
 * component and pass the `nonce` prop from the root Server Component layout.
 */
export default function MuiEmotionRegistry({ nonce, children }: Props) {
  const flushedNames = useRef(new Set<string>());

  const [cache] = useState(() => {
    const c = createCache({ key: 'css', nonce: nonce || undefined });
    c.compat = true;
    return c;
  });

  useServerInsertedHTML(() => {
    const newNames: string[] = [];
    for (const name of Object.keys(cache.inserted)) {
      if (!flushedNames.current.has(name)) {
        newNames.push(name);
        flushedNames.current.add(name);
      }
    }

    if (newNames.length === 0) return null;

    const styles = newNames
      .map((name) => cache.inserted[name])
      .filter((v): v is string => typeof v === 'string')
      .join('');

    if (!styles) return null;

    return (
      <style
        key={`mui-emotion-${newNames[0]}`}
        data-emotion={`${cache.key} ${newNames.join(' ')}`}
        nonce={nonce || undefined}
        dangerouslySetInnerHTML={{ __html: styles }}
      />
    );
  });

  return <CacheProvider value={cache}>{children}</CacheProvider>;
}
